[tool.poetry]
name = "planet-explorer"
version = "0.1.0"
description = ""
authors = ["Maria Laura <maria.raimundo@aluno.ufop.edu.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
